#h2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:jwt-token
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

jwt:
  expiration: 7200000
  secret: secret

server:
  port: 8085

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'